<?php

namespace App\Http\Requests;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\ValidationException;

class AcceptOrderValidator extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'id' => ['required'],
            'price'=>['required','numeric'],

        ];
    }

    /**
     * @return string[]
     */
    public function messages()
    {
        return
            [
                'required' => ':attribute is required',

            ];
    }
    /**
     * @return string[]
     */
    public function attributes()
    {
        return [

        ];
    }
    /**
     * @param Validator $validator
     * @throws \Illuminate\Validation\ValidationException
     */


    protected function failedValidation(Validator $validator)
    {
        if($this->wantsJson()){
            $response = response()->json([
                'success' => false,
                'message' => 'Error Validation',
                'errors' => $validator->errors()
            ],400);
        }      // TODO: Change the autogenerated stub
        throw(new ValidationException( $validator, $response));

    }
}
