/////////////////ADMIN////////////////

export const SIGN_IN_ADMIN_REQUEST = "SIGN_IN_ADMIN_REQUEST";
export const SIGN_IN_ADMIN_SUCCESS = "SIGN_IN_ADMIN_SUCCESS";
export const SIGN_IN_ADMIN_FAILURE = "SIGN_IN_ADMIN_FAILURE";

export const SIGN_UP_ADMIN_REQUEST = "SIGN_UP_ADMIN_REQUEST";
export const SIGN_UP_ADMIN_SUCCESS = "SIGN_UP_ADMIN_SUCCESS";
export const SIGN_UP_ADMIN_FAILURE = "SIGN_UP_ADMIN_FAILURE";

export const SIGN_OUT_ADMIN_REQUEST = "SIGN_OUT_ADMIN_REQUEST";
export const SIGN_OUT_ADMIN_SUCCESS = "SIGN_OUT_ADMIN_SUCCESS";
export const SIGN_OUT_ADMIN_FAILURE = "SIGN_OUT_ADMIN_FAILURE";

export const GET_ALL_SERVICES_PENDING_REQUEST_ADMIN = "GET_ALL_SERVICES_PENDING_REQUEST_ADMIN";
export const GET_ALL_SERVICES_PENDING_SUCCESS_ADMIN = "GET_ALL_SERVICES_PENDING_SUCCESS_ADMIN";
export const GET_ALL_SERVICES_PENDING_FAILURE_ADMIN = "GET_ALL_SERVICES_PENDING_FAILURE_ADMIN";

export const GET_ALL_SERVICES_ACCEPTED_REQUEST_ADMIN = "GET_ALL_SERVICES_ACCEPTED_REQUEST_ADMIN";
export const GET_ALL_SERVICES_ACCEPTED_SUCCESS_ADMIN = "GET_ALL_SERVICES_ACCEPTED_SUCCESS_ADMIN";
export const GET_ALL_SERVICES_ACCEPTED_FAILURE_ADMIN = "GET_ALL_SERVICES_ACCEPTED_FAILURE_ADMIN";

export const GET_ALL_SERVICES_REJECTED_REQUEST_ADMIN = "GET_ALL_SERVICES_REJECTED_REQUEST_ADMIN";
export const GET_ALL_SERVICES_REJECTED_SUCCESS_ADMIN = "GET_ALL_SERVICES_REJECTED_SUCCESS_ADMIN";
export const GET_ALL_SERVICES_REJECTED_FAILURE_ADMIN = "GET_ALL_SERVICES_REJECTED_FAILURE_ADMIN";
///////////USER/////////////

export const SIGN_IN_USER_REQUEST = "SIGN_IN_USER_REQUEST";
export const SIGN_IN_USER_SUCCESS = "SIGN_IN_USER_SUCCESS";
export const SIGN_IN_USER_FAILURE = "SIGN_IN_USER_FAILURE";

export const SIGN_UP_USER_REQUEST = "SIGN_UP_USER_REQUEST";
export const SIGN_UP_USER_SUCCESS = "SIGN_UP_USER_SUCCESS";
export const SIGN_UP_USER_FAILURE = "SIGN_UP_USER_FAILURE";

export const SIGN_OUT_USER_REQUEST = "SIGN_OUT_USER_REQUEST";
export const SIGN_OUT_USER_SUCCESS = "SIGN_OUT_USER_SUCCESS";
export const SIGN_OUT_USER_FAILURE = "SIGN_OUT_USER_FAILURE";

export const GET_ALL_CATEGORY_ACCEPTED_REQUEST_USER = "GET_ALL_CATEGORY_ACCEPTED_REQUEST_USER";
export const GET_ALL_CATEGORY_ACCEPTED_SUCCESS_USER = "GET_ALL_CATEGORY_ACCEPTED_SUCCESS_USER";
export const GET_ALL_CATEGORY_ACCEPTED_FAILED_USER = "GET_ALL_CATEGORY_ACCEPTED_FAILED_USER";

export const GET_ALL_CATEGORY_REQUEST_USER = "GET_ALL_CATEGORY_REQUEST_USER";
export const GET_ALL_CATEGORY_SUCCESS_USER = "GET_ALL_CATEGORY_SUCCESS_USER";
export const GET_ALL_CATEGORY_FAILED_USER = "GET_ALL_CATEGORY_FAILED_USER";

export const GET_SUBCATEGORY_BY_CATEGORY_ID_REQUEST_USER = "GET_SUBCATEGORY_BY_CATEGORY_ID_REQUEST_USER";
export const GET_SUBCATEGORY_BY_CATEGORY_ID_SUCCESS_USER = "GET_SUBCATEGORY_BY_CATEGORY_ID_SUCCESS_USER";
export const GET_SUBCATEGORY_BY_CATEGORY_ID_FAILED_USER = "GET_SUBCATEGORY_BY_CATEGORY_ID_FAILED_USER";
export const EMPTY_SUBCATEGORY = "EMPTY_SUBCATEGORY";

export const POST_CREATE_SERVICE_REQUEST_USER = "POST_CREATE_SERVICE_REQUEST_USER";
export const POST_CREATE_SERVICE_SUCCESS_USER = "POST_CREATE_SERVICE_SUCCESS_USER";
export const POST_CREATE_SERVICE_FAILED_USER = "POST_CREATE_SERVICE_FAILED_USER";

export const GET_ROOMS_REQUEST_USER = "GET_ROOMS_REQUEST_USER";
export const GET_ROOMS_SUCCESS_USER = "GET_ROOMS_SUCCESS_USER";
export const GET_ROOMS_FAILED_USER = "GET_ROOMS_FAILED_USER";

export const CONTACT_SELLER_REQUEST_USER = "CONTACT_SELLER_REQUEST_USER";
export const CONTACT_SELLER_SUCCESS_USER = "CONTACT_SELLER_SUCCESS_USER";
export const CONTACT_SELLER_FAILED_USER = "CONTACT_SELLER_FAILED_USER";


export const ACCCEPT_SERVICE_REQUEST_ADMIN = "ACCCEPT_SERVICE_REQUEST_ADMIN";
export const ACCCEPT_SERVICE_SUCCESS_ADMIN = "ACCCEPT_SERVICE_SUCCESS_ADMIN";
export const ACCCEPT_SERVICE_FAILED_ADMIN = "ACCCEPT_SERVICE_FAILED_ADMIN";

export const REJECT_SERVICE_PENDING_REQUEST_ADMIN = "REJECT_SERVICE_PENDING_REQUEST_ADMIN";
export const REJECT_SERVICE_PENDING_SUCCESS_ADMIN = "REJECT_SERVICE_PENDING_SUCCESS_ADMIN";
export const REJECT_SERVICE_PENDING_FAILED_ADMIN = "REJECT_SERVICE_PENDING_FAILED_ADMIN";

export const POST_ORDER_REQUEST_USER = "POST_ORDER_REQUEST_USER";
export const POST_ORDER_SUCCESS_USER = "POST_ORDER_SUCCESS_USER";
export const POST_ORDER_FAILED_USER = "POST_ORDER_FAILED_USER";


export const ACCEPTED = "ACCEPTED";
export const PENDING = "PENDING";
export const REJECTED = "REJECTED";

export const GET_ALL_SUCATEGORY_CATEGORY_SERVICE_REQUEST_GUEST = "GET_ALL_SUCATEGORY_CATEGORY_SERVICE_REQUEST_GUEST";
export const GET_ALL_SUCATEGORY_CATEGORY_SERVICE_SUCCESS_GUEST = "GET_ALL_SUCATEGORY_CATEGORY_SERVICE_SUCCESS_GUEST";
export const GET_ALL_SUCATEGORY_CATEGORY_SERVICE_FAILED_GUEST = "GET_ALL_SUCATEGORY_CATEGORY_SERVICE_FAILED_GUEST";

export const GET_ALL_SUB_ILLUSTRATOR_SERVICE_REQUEST_GUEST = "GET_ALL_SUB_ILLUSTRATOR_SERVICE_REQUEST_GUEST";
export const GET_ALL_SUB_ILLUSTRATOR_SERVICE_SUCCESS_GUEST = "GET_ALL_SUB_ILLUSTRATOR_SERVICE_SUCCESS_GUEST";
export const GET_ALL_SUB_ILLUSTRATOR_SERVICE_FAILED_GUEST = "GET_ALL_SUB_ILLUSTRATOR_SERVICE_FAILED_GUEST";

export const ACCEPTED_SERVICES = "ACCEPTED_SERVICES";


